## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [0]:
import tensorflow as tf

In [46]:
!pip show tensorflow

Name: tensorflow
Version: 1.14.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: wrapt, tensorboard, numpy, google-pasta, astor, gast, absl-py, protobuf, grpcio, wheel, keras-preprocessing, termcolor, six, keras-applications, tensorflow-estimator
Required-by: stable-baselines, magenta, fancyimpute

In [0]:
tf.enable_eager_execution()

In [0]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default

### Collect Data

In [3]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [0]:
import pandas as pd

In [0]:
data = pd.read_csv('/content/drive/My Drive/Lab/11_Iris.csv')

In [0]:
data_p = pd.read_csv('/content/drive/My Drive/Lab/prices.csv')

### Check all columns in the dataset

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB

In [8]:
data_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB

### Drop columns `date` and  `symbol`

In [0]:
data_p = data_p.drop(['date','symbol'], axis=1)

In [10]:
data_p.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [11]:
data_p = data_p.head(1000)
data_p.shape

(1000, 5)

In [12]:
data_p['volume'] = data_p['volume']/1000000
data_p.head()

         open       close         low        high  volume
0  123.430000  125.839996  122.309998  126.250000  2.1636
1  125.239998  119.980003  119.940002  125.540001  2.3864
2  116.379997  114.949997  114.930000  119.739998  2.4895
3  115.480003  116.620003  113.500000  117.440002  2.0063
4  117.010002  114.970001  114.089996  117.330002  1.4086

### Divide the data into train and test sets

In [0]:
from sklearn.model_selection import train_test_split
X = data_p.drop('volume', axis=1)
y = data_p['volume']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

In [14]:
X_train.shape

(700, 4)

In [15]:
y_train.shape

(700,)

#### Convert Training and Test Data to numpy float32 arrays

In [16]:
import numpy as np
X_train = X_train.values
X_train = np.float32(X_train)
X_train.dtype

dtype('float32')

In [17]:
X_test = X_test.values
X_test = np.float32(X_test)
X_test.dtype

dtype('float32')

In [18]:
y_train = y_train.values
y_train = np.float32(y_train)
y_train.dtype

dtype('float32')

In [19]:
y_test = y_test.values
y_test = np.float32(y_test)
y_test.dtype

dtype('float32')

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [0]:
from sklearn.preprocessing import Normalizer
transformer = Normalizer().fit(X_train)

X_train_n = transformer.transform(X_train)
X_test_n = transformer.transform(X_test)

In [21]:
X_train_n

array([[0.50021225, 0.5003598 , 0.49549326, 0.503899  ],
       [0.5023256 , 0.50103617, 0.4931476 , 0.5034255 ],
       [0.5004301 , 0.49899533, 0.4962851 , 0.5042563 ],
       ...,
       [0.5001929 , 0.49977148, 0.4976645 , 0.50236005],
       [0.50253594, 0.49852157, 0.496339  , 0.50257486],
       [0.50121456, 0.4987676 , 0.49595362, 0.5040285 ]], dtype=float32)

In [22]:
X_test_n

array([[0.5063693 , 0.49396917, 0.4904527 , 0.50896037],
       [0.49942613, 0.50043815, 0.49706477, 0.5030525 ],
       [0.4963037 , 0.50399053, 0.49479976, 0.50482607],
       ...,
       [0.49629417, 0.50301725, 0.49192008, 0.5086063 ],
       [0.49930164, 0.5008185 , 0.49753195, 0.50233537],
       [0.49550715, 0.50393987, 0.49483255, 0.50562644]], dtype=float32)

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [0]:
W = tf.Variable(tf.random_normal(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

In [25]:
W.numpy()

array([[-0.6688736 ],
       [-0.08423305],
       [ 1.769338  ],
       [ 0.48243293]], dtype=float32)

2.Define a function to calculate prediction

In [0]:
def prediction(X_train_n, W, b):
  return tf.add(tf.matmul(X_train_n,W),b,name='output')

3.Loss (Cost) Function [Mean square error]

In [0]:
def loss_c(X_train_n, y_train, W, b):
  return tf.reduce_mean(tf.square(y_train-prediction(X_train_n, W, b)),name='Loss')

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def training(X_train_n, y_train, W, b, learning_rate = 0.03):
  with tf.GradientTape() as tape:
    tape.watch([W, b])
    loss = loss_c(X_train_n, y_train, W, b)
  dW,db = tape.gradient(loss,[W,b])
  W = W - learning_rate * dW
  b = b - learning_rate * db
  return W,b

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [65]:
for epoch in range(100):
  W1,b1 = training(X_train_n, y_train, W, b, learning_rate = 0.03)
  if epoch % 5 == 0:
        print ('Training loss at step: ', epoch, ' is ', loss_c(X_train_n, y_train, W1, b1))

Training loss at step:  0  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  5  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  10  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  15  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  20  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  25  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  30  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  35  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  40  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  45  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  50  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  55  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  60  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  65  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  70  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  75  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  80  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  85  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  90  is  tf.Tensor(292.3076, shape=(), dtype=float32)
Training loss at step:  95  is  tf.Tensor(292.3076, shape=(), dtype=float32)

Using TensorFlow backend.

### Get the shapes and values of W and b

In [66]:
W1.numpy()

array([[-0.52301705],
       [ 0.0621268 ],
       [ 1.9136932 ],
       [ 0.630022  ]], dtype=float32)

In [67]:
b1.numpy()

array([0.29209635], dtype=float32)

### Model Prediction on 1st Examples in Test Dataset

In [68]:
X_test_n[0:1]

array([[0.5063693 , 0.49396917, 0.4904527 , 0.50896037]], dtype=float32)

In [0]:
y_pred_1st = prediction(X_test_n[0:1], W1, b1)

In [72]:
y_pred_1st.numpy()

array([[1.3171775]], dtype=float32)

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [0]:
y = pd.get_dummies(data['Species'])

In [86]:
y.head()

   Iris-setosa  Iris-versicolor  Iris-virginica
0            1                0               0
1            1                0               0
2            1                0               0
3            1                0               0
4            1                0               0

In [0]:
X = data.drop('Species', axis=1)
X = X.drop('Id', axis=1)

In [91]:
X.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

### Splitting the data into feature set and target set

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [97]:
X_train.shape

(120, 4)

In [98]:
X_test.shape

(30, 4)

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

In [0]:

# create model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(4, input_dim=4, activation='tanh'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

### Model Training

In [116]:
# Fit the model
model.fit(X_train, y_train, epochs=135, batch_size=10)

Epoch 1/135
120/120 [==============================] - 0s 420us/sample - loss: 0.4833 - acc: 0.7333
Epoch 2/135
120/120 [==============================] - 0s 301us/sample - loss: 0.4830 - acc: 0.7583
Epoch 3/135
120/120 [==============================] - 0s 333us/sample - loss: 0.4829 - acc: 0.7167
Epoch 4/135
120/120 [==============================] - 0s 329us/sample - loss: 0.4823 - acc: 0.7333
Epoch 5/135
120/120 [==============================] - 0s 310us/sample - loss: 0.4826 - acc: 0.7250
Epoch 6/135
120/120 [==============================] - 0s 323us/sample - loss: 0.4816 - acc: 0.7250
Epoch 7/135
120/120 [==============================] - 0s 300us/sample - loss: 0.4814 - acc: 0.7500
Epoch 8/135
120/120 [==============================] - 0s 288us/sample - loss: 0.4815 - acc: 0.7917
Epoch 9/135
120/120 [==============================] - 0s 293us/sample - loss: 0.4807 - acc: 0.7333
Epoch 10/135
120/120 [==============================] - 0s 283us/sample - loss: 0.4800 - acc: 0.7750
Epoch 11/135
120/120 [==============================] - 0s 299us/sample - loss: 0.4799 - acc: 0.7333
Epoch 12/135
120/120 [==============================] - 0s 290us/sample - loss: 0.4796 - acc: 0.7417
Epoch 13/135
120/120 [==============================] - 0s 284us/sample - loss: 0.4790 - acc: 0.7333
Epoch 14/135
120/120 [==============================] - 0s 325us/sample - loss: 0.4788 - acc: 0.7417
Epoch 15/135
120/120 [==============================] - 0s 325us/sample - loss: 0.4791 - acc: 0.7583
Epoch 16/135
120/120 [==============================] - 0s 321us/sample - loss: 0.4784 - acc: 0.7500
Epoch 17/135
120/120 [==============================] - 0s 372us/sample - loss: 0.4781 - acc: 0.8083
Epoch 18/135
120/120 [==============================] - 0s 365us/sample - loss: 0.4776 - acc: 0.7417
Epoch 19/135
120/120 [==============================] - 0s 349us/sample - loss: 0.4775 - acc: 0.7417
Epoch 20/135
120/120 [==============================] - 0s 384us/sample - loss: 0.4765 - acc: 0.7417
Epoch 21/135
120/120 [==============================] - 0s 318us/sample - loss: 0.4766 - acc: 0.7667
Epoch 22/135
120/120 [==============================] - 0s 280us/sample - loss: 0.4758 - acc: 0.7833
Epoch 23/135
120/120 [==============================] - 0s 307us/sample - loss: 0.4762 - acc: 0.8000
Epoch 24/135
120/120 [==============================] - 0s 269us/sample - loss: 0.4753 - acc: 0.7417
Epoch 25/135
120/120 [==============================] - 0s 266us/sample - loss: 0.4748 - acc: 0.7667
Epoch 26/135
120/120 [==============================] - 0s 330us/sample - loss: 0.4743 - acc: 0.7583
Epoch 27/135
120/120 [==============================] - 0s 336us/sample - loss: 0.4740 - acc: 0.7500
Epoch 28/135
120/120 [==============================] - 0s 304us/sample - loss: 0.4736 - acc: 0.7583
Epoch 29/135
120/120 [==============================] - 0s 304us/sample - loss: 0.4733 - acc: 0.7583
Epoch 30/135
120/120 [==============================] - 0s 335us/sample - loss: 0.4729 - acc: 0.7500
Epoch 31/135
120/120 [==============================] - 0s 313us/sample - loss: 0.4728 - acc: 0.7833
Epoch 32/135
120/120 [==============================] - 0s 296us/sample - loss: 0.4725 - acc: 0.8000
Epoch 33/135
120/120 [==============================] - 0s 309us/sample - loss: 0.4726 - acc: 0.8000
Epoch 34/135
120/120 [==============================] - 0s 276us/sample - loss: 0.4712 - acc: 0.7750
Epoch 35/135
120/120 [==============================] - 0s 314us/sample - loss: 0.4718 - acc: 0.7583
Epoch 36/135
120/120 [==============================] - 0s 309us/sample - loss: 0.4707 - acc: 0.8083
Epoch 37/135
120/120 [==============================] - 0s 292us/sample - loss: 0.4699 - acc: 0.7917
Epoch 38/135
120/120 [==============================] - 0s 263us/sample - loss: 0.4695 - acc: 0.7750
Epoch 39/135
120/120 [==============================] - 0s 279us/sample - loss: 0.4699 - acc: 0.7917
Epoch 40/135
120/120 [==============================] - 0s 268us/sample - loss: 0.4692 - acc: 0.7750
Epoch 41/135
120/120 [==============================] - 0s 310us/sample - loss: 0.4686 - acc: 0.8083
Epoch 42/135
120/120 [==============================] - 0s 322us/sample - loss: 0.4687 - acc: 0.8083
Epoch 43/135
120/120 [==============================] - 0s 380us/sample - loss: 0.4682 - acc: 0.8000
Epoch 44/135
120/120 [==============================] - 0s 375us/sample - loss: 0.4680 - acc: 0.8000
Epoch 45/135
120/120 [==============================] - 0s 318us/sample - loss: 0.4674 - acc: 0.8083
Epoch 46/135
120/120 [==============================] - 0s 338us/sample - loss: 0.4663 - acc: 0.8250
Epoch 47/135
120/120 [==============================] - 0s 355us/sample - loss: 0.4659 - acc: 0.8167
Epoch 48/135
120/120 [==============================] - 0s 310us/sample - loss: 0.4659 - acc: 0.8333
Epoch 49/135
120/120 [==============================] - 0s 328us/sample - loss: 0.4655 - acc: 0.8167
Epoch 50/135
120/120 [==============================] - 0s 325us/sample - loss: 0.4648 - acc: 0.8167
Epoch 51/135
120/120 [==============================] - 0s 300us/sample - loss: 0.4650 - acc: 0.8250
Epoch 52/135
120/120 [==============================] - 0s 345us/sample - loss: 0.4636 - acc: 0.8167
Epoch 53/135
120/120 [==============================] - 0s 340us/sample - loss: 0.4634 - acc: 0.8167
Epoch 54/135
120/120 [==============================] - 0s 319us/sample - loss: 0.4631 - acc: 0.8250
Epoch 55/135
120/120 [==============================] - 0s 356us/sample - loss: 0.4623 - acc: 0.8167
Epoch 56/135
120/120 [==============================] - 0s 299us/sample - loss: 0.4618 - acc: 0.8167
Epoch 57/135
120/120 [==============================] - 0s 315us/sample - loss: 0.4620 - acc: 0.7833
Epoch 58/135
120/120 [==============================] - 0s 312us/sample - loss: 0.4609 - acc: 0.8333
Epoch 59/135
120/120 [==============================] - 0s 308us/sample - loss: 0.4608 - acc: 0.8250
Epoch 60/135
120/120 [==============================] - 0s 306us/sample - loss: 0.4600 - acc: 0.8417
Epoch 61/135
120/120 [==============================] - 0s 292us/sample - loss: 0.4594 - acc: 0.8333
Epoch 62/135
120/120 [==============================] - 0s 300us/sample - loss: 0.4590 - acc: 0.8250
Epoch 63/135
120/120 [==============================] - 0s 268us/sample - loss: 0.4581 - acc: 0.8333
Epoch 64/135
120/120 [==============================] - 0s 286us/sample - loss: 0.4582 - acc: 0.8333
Epoch 65/135
120/120 [==============================] - 0s 307us/sample - loss: 0.4574 - acc: 0.8333
Epoch 66/135
120/120 [==============================] - 0s 318us/sample - loss: 0.4573 - acc: 0.8583
Epoch 67/135
120/120 [==============================] - 0s 385us/sample - loss: 0.4564 - acc: 0.8250
Epoch 68/135
120/120 [==============================] - 0s 341us/sample - loss: 0.4558 - acc: 0.8250
Epoch 69/135
120/120 [==============================] - 0s 288us/sample - loss: 0.4549 - acc: 0.8250
Epoch 70/135
120/120 [==============================] - 0s 297us/sample - loss: 0.4547 - acc: 0.8417
Epoch 71/135
120/120 [==============================] - 0s 338us/sample - loss: 0.4539 - acc: 0.8500
Epoch 72/135
120/120 [==============================] - 0s 325us/sample - loss: 0.4540 - acc: 0.8417
Epoch 73/135
120/120 [==============================] - 0s 300us/sample - loss: 0.4526 - acc: 0.8250
Epoch 74/135
120/120 [==============================] - 0s 297us/sample - loss: 0.4524 - acc: 0.8167
Epoch 75/135
120/120 [==============================] - 0s 299us/sample - loss: 0.4515 - acc: 0.8583
Epoch 76/135
120/120 [==============================] - 0s 289us/sample - loss: 0.4509 - acc: 0.8250
Epoch 77/135
120/120 [==============================] - 0s 420us/sample - loss: 0.4505 - acc: 0.8417
Epoch 78/135
120/120 [==============================] - 0s 399us/sample - loss: 0.4495 - acc: 0.8667
Epoch 79/135
120/120 [==============================] - 0s 293us/sample - loss: 0.4487 - acc: 0.8417
Epoch 80/135
120/120 [==============================] - 0s 303us/sample - loss: 0.4485 - acc: 0.8417
Epoch 81/135
120/120 [==============================] - 0s 368us/sample - loss: 0.4475 - acc: 0.8333
Epoch 82/135
120/120 [==============================] - 0s 293us/sample - loss: 0.4473 - acc: 0.8583
Epoch 83/135
120/120 [==============================] - 0s 311us/sample - loss: 0.4471 - acc: 0.8333
Epoch 84/135
120/120 [==============================] - 0s 338us/sample - loss: 0.4455 - acc: 0.8583
Epoch 85/135
120/120 [==============================] - 0s 315us/sample - loss: 0.4455 - acc: 0.8417
Epoch 86/135
120/120 [==============================] - 0s 277us/sample - loss: 0.4445 - acc: 0.8500
Epoch 87/135
120/120 [==============================] - 0s 288us/sample - loss: 0.4436 - acc: 0.8417
Epoch 88/135
120/120 [==============================] - 0s 316us/sample - loss: 0.4431 - acc: 0.8500
Epoch 89/135
120/120 [==============================] - 0s 282us/sample - loss: 0.4422 - acc: 0.8500
Epoch 90/135
120/120 [==============================] - 0s 332us/sample - loss: 0.4423 - acc: 0.8583
Epoch 91/135
120/120 [==============================] - 0s 470us/sample - loss: 0.4412 - acc: 0.8750
Epoch 92/135
120/120 [==============================] - 0s 334us/sample - loss: 0.4403 - acc: 0.8500
Epoch 93/135
120/120 [==============================] - 0s 316us/sample - loss: 0.4391 - acc: 0.8667
Epoch 94/135
120/120 [==============================] - 0s 349us/sample - loss: 0.4389 - acc: 0.8833
Epoch 95/135
120/120 [==============================] - 0s 332us/sample - loss: 0.4378 - acc: 0.8667
Epoch 96/135
120/120 [==============================] - 0s 285us/sample - loss: 0.4376 - acc: 0.8750
Epoch 97/135
120/120 [==============================] - 0s 300us/sample - loss: 0.4361 - acc: 0.8583
Epoch 98/135
120/120 [==============================] - 0s 281us/sample - loss: 0.4354 - acc: 0.8750
Epoch 99/135
120/120 [==============================] - 0s 289us/sample - loss: 0.4345 - acc: 0.8667
Epoch 100/135
120/120 [==============================] - 0s 310us/sample - loss: 0.4333 - acc: 0.8417
Epoch 101/135
120/120 [==============================] - 0s 352us/sample - loss: 0.4330 - acc: 0.8750
Epoch 102/135
120/120 [==============================] - 0s 331us/sample - loss: 0.4315 - acc: 0.9000
Epoch 103/135
120/120 [==============================] - 0s 294us/sample - loss: 0.4323 - acc: 0.8667
Epoch 104/135
120/120 [==============================] - 0s 332us/sample - loss: 0.4302 - acc: 0.8833
Epoch 105/135
120/120 [==============================] - 0s 296us/sample - loss: 0.4303 - acc: 0.8750
Epoch 106/135
120/120 [==============================] - 0s 329us/sample - loss: 0.4289 - acc: 0.8667
Epoch 107/135
120/120 [==============================] - 0s 292us/sample - loss: 0.4285 - acc: 0.8833
Epoch 108/135
120/120 [==============================] - 0s 292us/sample - loss: 0.4263 - acc: 0.8750
Epoch 109/135
120/120 [==============================] - 0s 327us/sample - loss: 0.4269 - acc: 0.9000
Epoch 110/135
120/120 [==============================] - 0s 311us/sample - loss: 0.4246 - acc: 0.8750
Epoch 111/135
120/120 [==============================] - 0s 302us/sample - loss: 0.4246 - acc: 0.8833
Epoch 112/135
120/120 [==============================] - 0s 327us/sample - loss: 0.4237 - acc: 0.9000
Epoch 113/135
120/120 [==============================] - 0s 282us/sample - loss: 0.4227 - acc: 0.9000
Epoch 114/135
120/120 [==============================] - 0s 295us/sample - loss: 0.4218 - acc: 0.9000
Epoch 115/135
120/120 [==============================] - 0s 403us/sample - loss: 0.4219 - acc: 0.8833
Epoch 116/135
120/120 [==============================] - 0s 272us/sample - loss: 0.4198 - acc: 0.8833
Epoch 117/135
120/120 [==============================] - 0s 308us/sample - loss: 0.4181 - acc: 0.8833
Epoch 118/135
120/120 [==============================] - 0s 290us/sample - loss: 0.4183 - acc: 0.8917
Epoch 119/135
120/120 [==============================] - 0s 281us/sample - loss: 0.4172 - acc: 0.8917
Epoch 120/135
120/120 [==============================] - 0s 377us/sample - loss: 0.4165 - acc: 0.8833
Epoch 121/135
120/120 [==============================] - 0s 289us/sample - loss: 0.4167 - acc: 0.8917
Epoch 122/135
120/120 [==============================] - 0s 278us/sample - loss: 0.4155 - acc: 0.8917
Epoch 123/135
120/120 [==============================] - 0s 291us/sample - loss: 0.4129 - acc: 0.8917
Epoch 124/135
120/120 [==============================] - 0s 311us/sample - loss: 0.4132 - acc: 0.9083
Epoch 125/135
120/120 [==============================] - 0s 315us/sample - loss: 0.4121 - acc: 0.9000
Epoch 126/135
120/120 [==============================] - 0s 331us/sample - loss: 0.4121 - acc: 0.9167
Epoch 127/135
120/120 [==============================] - 0s 316us/sample - loss: 0.4112 - acc: 0.8917
Epoch 128/135
120/120 [==============================] - 0s 316us/sample - loss: 0.4102 - acc: 0.9000
Epoch 129/135
120/120 [==============================] - 0s 318us/sample - loss: 0.4084 - acc: 0.9000
Epoch 130/135
120/120 [==============================] - 0s 325us/sample - loss: 0.4088 - acc: 0.8917
Epoch 131/135
120/120 [==============================] - 0s 304us/sample - loss: 0.4080 - acc: 0.9000
Epoch 132/135
120/120 [==============================] - 0s 307us/sample - loss: 0.4059 - acc: 0.8917
Epoch 133/135
120/120 [==============================] - 0s 306us/sample - loss: 0.4052 - acc: 0.9083
Epoch 134/135
120/120 [==============================] - 0s 301us/sample - loss: 0.4036 - acc: 0.9250
Epoch 135/135
120/120 [==============================] - 0s 297us/sample - loss: 0.4041 - acc: 0.8833

In [117]:
# evaluate the model
scores = model.evaluate(X_train, y_train)
scores[1]*100

120/120 [==============================] - 0s 485us/sample - loss: 0.4014 - acc: 0.9167

91.66666865348816

### Model Prediction

In [0]:
y_predict=model.predict_classes(X_test)

### Save the Model

In [0]:
model.save("keras_model.h5")

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?